{
 "title": "Caching dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Cache hit/miss ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((cache_gets_total{result=\"hit\"}) / ignoring(result)( cache_gets_total{result=\"miss\"}))",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(cache_gets_total{result=\"hit\"}[1m])",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Cache misses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(cache_gets_total{result=\"miss\"}[1m])",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Cache evicts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "rate(cache_removals_total[1m])", "legendFormat": "{{cache}}" }
   ]
  }
 ]
}