{
 "title": "Hibernate Statistics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Hibernate optimistic failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(hibernate_optimistic_failures_total[1m])",
     "legendFormat": "{{entityManagerFactory}}"
    }
   ]
  },
  {
   "title": "Hibernate connections obtained",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(hibernate_connections_obtained_total[1m])",
     "legendFormat": "{{entitiManagerFactory}}"
    }
   ]
  },
  {
   "title": "Hibernate statements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(hibernate_statements_total[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Hibernate transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(hibernate_transactions_total[1m])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Hibernate entities updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "rate(hibernate_entities_updates_total[1m])",
     "legendFormat": "{{entitiManagerFactory}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "HIbernate entities deletes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(hibernate_entities_deletes_total[1m])",
     "legendFormat": "{{entitiManagerFactory}}"
    }
   ]
  },
  {
   "title": "Hibernate Entities inserts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(hibernate_entities_inserts_total[1m])"
    }
   ]
  },
  {
   "title": "Hibernate entities load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(hibernate_entities_loads_total[1m])"
    }
   ]
  }
 ]
}