{
 "title": "Spring data JPA",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "UserRepository calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(spring_data_repository_invocations_seconds_count{repository=\"UserRepository\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "UserRoleRepository calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(spring_data_repository_invocations_seconds_count{repository=\"UserRoleRepository\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "InvestmentRepository calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(spring_data_repository_invocations_seconds_count{repository=\"InvestmentRepository\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "InvestmentRecordRepository calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(spring_data_repository_invocations_seconds_count{repository=\"InvestmentRecordRepository\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}